# Generated by Django 4.1 on 2023-11-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="boss_form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_dogovor", models.TextField()),
                ("remark_name", models.TextField()),
                ("executor_fail_name", models.TextField()),
                ("executor_name", models.TextField()),
                ("answer_date_plan", models.DateField()),
                ("answer_deadline_correct_plan", models.DateField()),
                ("labor_costs_plan", models.FloatField()),
                ("important_remark", models.TextField()),
                ("accept_important_remark", models.BooleanField()),
                ("comment", models.TextField()),
                ("root_cause_list", models.TextField()),
                ("link_tech_name", models.TextField()),
                ("answer_remark", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="GIP_form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_reestr", models.TextField()),
                ("project_dogovor", models.TextField()),
                ("project_date_contract", models.DateField()),
                ("project_name", models.TextField()),
                ("project_reviewer", models.TextField()),
                ("num_message_out", models.TextField()),
                ("date_message_out", models.DateField()),
                ("num_message_in", models.TextField()),
                ("date_message_in", models.DateField()),
                ("remark_name", models.TextField()),
                ("designation_name", models.TextField()),
                ("section_name", models.TextField()),
                ("responsibleTrouble_name", models.TextField()),
            ],
        ),
    ]
