# Generated by Django 4.1 on 2023-11-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0002_reestr_delete_boss_form_delete_gip_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reestr",
            name="importance1",
            field=models.BooleanField(
                blank=None,
                choices=[(True, "Требуется"), (False, "Не требуется")],
                default=None,
                verbose_name="Корректировка документации (свой раздел, глава, том, книга, др. док.)",
            ),
        ),
    ]
