# Generated by Django 4.1 on 2023-11-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0003_alter_reestr_importance1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reestr",
            name="importance2",
            field=models.BooleanField(
                blank=None,
                choices=[(True, "Требуется"), (False, "Не требуется")],
                default=None,
                verbose_name="Корректировка смежных разделов (глав, томов, др. док.)",
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="importance3",
            field=models.BooleanField(
                blank=None,
                choices=[(True, "Требуется"), (False, "Не требуется")],
                default=None,
                verbose_name="Выдача задания смежным подразделениям (без учёта ОКиВД) и (или) получение исходных данных от них",
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="importance4",
            field=models.BooleanField(
                blank=None,
                choices=[(True, "Требуется"), (False, "Не требуется")],
                default=None,
                verbose_name="Корректировка принятых проектных решений",
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="importance5",
            field=models.BooleanField(
                blank=None,
                choices=[(True, "Требуется"), (False, "Не требуется")],
                default=None,
                verbose_name="Получение дополнительных исходных данных от Заказчика",
            ),
        ),
    ]
