# Generated by Django 4.1 on 2023-11-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0004_alter_reestr_importance2_alter_reestr_importance3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reestr",
            name="importance6",
            field=models.BooleanField(
                blank=None,
                choices=[
                    (True, "Вина/Инициатива Заказчика"),
                    (False, "Вина проектировщика"),
                ],
                default=None,
                verbose_name="Корректировка принятых проектных решений требуется по причине:",
            ),
        ),
        migrations.AddField(
            model_name="reestr",
            name="importance7",
            field=models.BooleanField(
                blank=None,
                choices=[(True, "Да"), (False, "Нет")],
                default=None,
                verbose_name="Нарушены требования нормативно-технических документов:",
            ),
        ),
    ]
