# Generated by Django 4.1 on 2023-12-01 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0005_reestr_importance6_reestr_importance7"),
    ]

    operations = [
        migrations.AddField(
            model_name="reestr",
            name="customer",
            field=models.TextField(default="", verbose_name="Заказчик"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reestr",
            name="gip",
            field=models.TextField(default="", verbose_name="ГИП"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reestr",
            name="in_mail_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Письмо вх. дата"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reestr",
            name="in_mail_num",
            field=models.TextField(default=1, verbose_name="Письмо вх. №"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reestr",
            name="out_mail_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Письмо исх. дата"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reestr",
            name="out_mail_num",
            field=models.TextField(default=1, verbose_name="Письмо исх. №"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reestr",
            name="remark_v",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reestr",
            name="num_reestr",
            field=models.TextField(verbose_name="1. Реестр №"),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="project_dogovor",
            field=models.TextField(verbose_name="Договор №"),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="responsibleTrouble_name",
            field=models.TextField(
                verbose_name="5. Ответственный за устранение замечаний (начальник подразделения)"
            ),
        ),
    ]
