# Generated by Django 4.1 on 2023-12-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0006_reestr_customer_reestr_gip_reestr_in_mail_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reestr",
            name="project_date_contract",
            field=models.DateField(blank=True, verbose_name="Дата договора"),
        ),
    ]
