# Generated by Django 4.1 on 2023-12-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0008_alter_reestr_project_date_contract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reestr",
            name="project_date_contract",
            field=models.DateField(blank=True, verbose_name="Дата договора"),
        ),
    ]
