# Generated by Django 4.1 on 2023-12-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0009_alter_reestr_project_date_contract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reestr",
            name="answer_date_fact",
            field=models.DateField(
                blank=True,
                verbose_name="8. Дата предоставления ответов на замечания (Факт)",
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="answer_date_plan",
            field=models.DateField(
                blank=True,
                verbose_name="7. Дата предоставления ответов на замечания (План)",
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="answer_deadline_correct_fact",
            field=models.DateField(
                blank=True, verbose_name="10. Срок внесения корректировок (Факт)"
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="answer_deadline_correct_plan",
            field=models.DateField(
                blank=True, verbose_name="9. Срок внесения корректировок (План)"
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="cancel_remark",
            field=models.DateField(
                blank=True, verbose_name="13. Отметка о снятии замечания, дата"
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="in_mail_date",
            field=models.DateField(blank=True, verbose_name="Письмо вх. дата"),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="out_mail_date",
            field=models.DateField(blank=True, verbose_name="Письмо исх. дата"),
        ),
    ]
