# Generated by Django 4.1 on 2023-12-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0011_alter_reestr_remark_v"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reestr",
            name="root_cause_list",
            field=models.TextField(verbose_name="15. Коренная причина"),
        ),
    ]
