# Generated by Django 4.1 on 2023-12-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0012_alter_reestr_root_cause_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reestr",
            name="importance1",
        ),
        migrations.RemoveField(
            model_name="reestr",
            name="importance2",
        ),
        migrations.RemoveField(
            model_name="reestr",
            name="importance3",
        ),
        migrations.RemoveField(
            model_name="reestr",
            name="importance4",
        ),
        migrations.RemoveField(
            model_name="reestr",
            name="importance5",
        ),
        migrations.RemoveField(
            model_name="reestr",
            name="importance6",
        ),
        migrations.RemoveField(
            model_name="reestr",
            name="importance7",
        ),
        migrations.AlterField(
            model_name="reestr",
            name="answer_remark",
            field=models.TextField(blank=True, verbose_name="11. Ответы на замечания"),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="comment",
            field=models.TextField(blank=True, verbose_name="10.3. Комментарии"),
        ),
    ]
