# Generated by Django 4.1 on 2023-12-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "formapp",
            "0013_remove_reestr_importance1_remove_reestr_importance2_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reestr",
            name="executor_fail_name",
            field=models.TextField(
                blank=True, verbose_name="6. Исполнитель, допустивший замечание"
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="executor_name",
            field=models.TextField(
                blank=True,
                verbose_name="6.1. Исполнитель, ответственный за устранение замечания",
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="labor_costs_fact",
            field=models.FloatField(
                blank=True,
                verbose_name="10.2. Трудозатраты, дн. (на устранение замечания) (Факт)",
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="labor_costs_plan",
            field=models.FloatField(
                blank=True,
                verbose_name="10.1 Трудозатраты, дн. (на устранение замечания) (План)",
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="link_tech_name",
            field=models.TextField(
                blank=True, verbose_name="12. Ссылка  в  технической документации"
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="root_cause_list",
            field=models.TextField(blank=True, verbose_name="15. Коренная причина"),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="total_importance",
            field=models.TextField(blank=True, verbose_name="14. Значимость замечания"),
        ),
    ]
