# Generated by Django 4.1 on 2023-12-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0014_alter_reestr_executor_fail_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reestr",
            name="answer_date_fact",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="8. Дата предоставления ответов на замечания (Факт)",
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="answer_date_plan",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="7. Дата предоставления ответов на замечания (План)",
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="answer_deadline_correct_fact",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="10. Срок внесения корректировок (Факт)",
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="answer_deadline_correct_plan",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="9. Срок внесения корректировок (План)",
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="answer_remark",
            field=models.TextField(verbose_name="11. Ответы на замечания"),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="cancel_remark",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="13. Отметка о снятии замечания, дата",
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="comment",
            field=models.TextField(verbose_name="10.3. Комментарии"),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="executor_fail_name",
            field=models.TextField(
                verbose_name="6. Исполнитель, допустивший замечание"
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="executor_name",
            field=models.TextField(
                verbose_name="6.1. Исполнитель, ответственный за устранение замечания"
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="labor_costs_fact",
            field=models.FloatField(
                verbose_name="10.2. Трудозатраты, дн. (на устранение замечания) (Факт)"
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="labor_costs_plan",
            field=models.FloatField(
                verbose_name="10.1 Трудозатраты, дн. (на устранение замечания) (План)"
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="link_tech_name",
            field=models.TextField(
                verbose_name="12. Ссылка  в  технической документации"
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="root_cause_list",
            field=models.TextField(verbose_name="15. Коренная причина"),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="total_importance",
            field=models.TextField(verbose_name="14. Значимость замечания"),
        ),
    ]
