# Generated by Django 4.1 on 2023-12-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0015_alter_reestr_answer_date_fact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reestr",
            name="labor_costs_fact",
            field=models.FloatField(
                null=True,
                verbose_name="10.2. Трудозатраты, дн. (на устранение замечания) (Факт)",
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="labor_costs_plan",
            field=models.FloatField(
                null=True,
                verbose_name="10.1 Трудозатраты, дн. (на устранение замечания) (План)",
            ),
        ),
    ]
