# Generated by Django 4.1 on 2023-12-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0016_alter_reestr_labor_costs_fact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reestr",
            name="customer",
            field=models.TextField(
                error_messages={"required": "Введите данные"}, verbose_name="Заказчик"
            ),
        ),
    ]
