# Generated by Django 4.1 on 2023-12-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0017_alter_reestr_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reestr",
            name="customer",
            field=models.TextField(verbose_name="Заказчик"),
        ),
    ]
