# Generated by Django 4.1 on 2023-12-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0023_alter_reestr_comment_alter_reestr_root_cause_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reestr",
            name="labor_costs_plan",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="10.1 Трудозатраты, дн. (на устранение замечания) (План)",
            ),
        ),
    ]
