# Generated by Django 4.1 on 2024-01-22 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("formapp", "0025_alter_reestr_comment_alter_reestr_root_cause_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reestr",
            name="gip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ГИП",
            ),
        ),
    ]
