# Generated by Django 4.1 on 2024-01-22 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("formapp", "0028_alter_reestr_gip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reestr",
            name="gip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gip_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ГИП",
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="responsibleTrouble_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsTroble_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="5. Ответственный за устранение замечаний (начальник подразделения)",
            ),
        ),
    ]
