# Generated by Django 4.1 on 2024-02-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0031_alter_reestr_executor_fail_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reestr",
            name="add_files",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="",
                verbose_name="Дополнительные материалы",
            ),
        ),
    ]
