# Generated by Django 4.1 on 2024-02-07 12:20

from django.db import migrations, models
import formapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0032_reestr_add_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reestr",
            name="add_files",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=formapp.models.user_directory_path,
                verbose_name="Дополнительные материалы",
            ),
        ),
    ]
