# Generated by Django 4.1 on 2024-02-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0033_alter_reestr_add_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reestr",
            name="add_files",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/",
                verbose_name="Дополнительные материалы",
            ),
        ),
    ]
