# Generated by Django 4.1 on 2024-03-01 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("formapp", "0035_alter_reestr_executor_fail_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="reestInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer", models.TextField(verbose_name="Заказчик")),
                ("project_dogovor", models.TextField(verbose_name="Договор №")),
                (
                    "project_date_contract",
                    models.DateField(blank=True, verbose_name="Дата договора"),
                ),
                (
                    "project_name",
                    models.TextField(verbose_name="Наименование договора"),
                ),
                ("project_reviewer", models.TextField(verbose_name="Рецензент")),
                ("out_mail_num", models.TextField(verbose_name="Письмо исх. №")),
                (
                    "out_mail_date",
                    models.DateField(blank=True, verbose_name="Письмо исх. дата"),
                ),
                ("in_mail_num", models.TextField(verbose_name="Письмо вх. №")),
                (
                    "in_mail_date",
                    models.DateField(blank=True, verbose_name="Письмо вх. дата"),
                ),
                ("num_reestr", models.TextField(verbose_name="1. Реестр №")),
                (
                    "gip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gip_set1",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ГИП",
                    ),
                ),
            ],
        ),
    ]
