# Generated by Django 4.1 on 2024-03-01 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0036_reestinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="reestinfo",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
