# Generated by Django 4.1 on 2024-03-06 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0038_reestinfo_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="reestr",
            name="reestrID",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="formapp.reestinfo",
            ),
            preserve_default=False,
        ),
    ]
