# Generated by Django 4.1 on 2024-03-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0041_reestinfo_add_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="uploads/")),
                ("file_name", models.TextField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("upload_date", models.DateField()),
            ],
        ),
    ]
