# Generated by Django 4.1 on 2024-03-20 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0042_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="reestr",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="formapp.reestinfo",
            ),
            preserve_default=False,
        ),
    ]
