# Generated by Django 4.1 on 2024-03-20 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0043_files_reestr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reestinfo",
            name="add_files",
        ),
    ]
