# Generated by Django 4.1 on 2024-03-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0044_remove_reestinfo_add_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="file_size",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
