# Generated by Django 4.1 on 2024-03-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0045_files_file_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="upload_date",
            field=models.TextField(),
        ),
    ]
