# Generated by Django 4.1 on 2024-03-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0046_alter_files_upload_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="file_size",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="files",
            name="upload_date",
            field=models.DateField(),
        ),
    ]
