# Generated by Django 4.1 on 2024-03-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0047_alter_files_file_size_alter_files_upload_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="file_size",
            field=models.TextField(blank=True, null=True),
        ),
    ]
