# Generated by Django 4.1 on 2024-03-25 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0048_alter_files_file_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reestr",
            name="add_files",
        ),
        migrations.CreateModel(
            name="files2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="uploads/")),
                ("file_name", models.TextField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("file_size", models.TextField(blank=True, null=True)),
                ("upload_date", models.DateField()),
                (
                    "remark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="formapp.reestr"
                    ),
                ),
            ],
        ),
    ]
