# Generated by Django 4.1 on 2024-04-08 07:47

from django.db import migrations, models
import formapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0049_remove_reestr_add_files_files2"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="belong_to",
            field=models.TextField(default=1233),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="files",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=formapp.models.user_directory_path
            ),
        ),
    ]
