# Generated by Django 4.1 on 2024-04-16 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0051_reestinfo_step"),
    ]

    operations = [
        migrations.DeleteModel(
            name="files2",
        ),
    ]
